// clang-format off
// upload_speed 921600
// board ttgo-t-beam

#ifndef _AXP202_BOARD_H
#define _AXP202_BOARD_H

#include <stdint.h>

/* 
Hardware related definitions for some unknown board with AXP202 power management chip

/// Button functions: ///
Power, short press -> set device on / while device is on: goto sleep
Power, long press   -> set device off
User, short press   -> flip display page 
User, long press    -> send a button message
Reset -> reset device
*/

#define HAS_DISPLAY 1
#define MY_DISPLAY_SDA SDA
#define MY_DISPLAY_SCL SCL
#define MY_DISPLAY_RST NOT_A_PIN
//#define MY_DISPLAY_FLIP  1 // use if display is rotated

#define HAS_LORA 1       // comment out if device shall not send data via LoRa
#define CFG_sx1276_radio 1 // HPD13A LoRa SoC
#define HAS_BUTTON GPIO_NUM_38 // middle on board button
#define HAS_LED GPIO_NUM_4 // not present on all T-Beam 1.0 boards
#define LED_ACTIVE_LOW 1

// power management settings
#define HAS_PMU 1 // has AXP202 chip
#define XPOWERS_CHIP_AXP202 1
#define PMU_INT GPIO_NUM_35 // battery interrupt
#define PMU_CHG_CURRENT XPOWERS_AXP202_CHG_CUR_1000MA // battery charge current
// See: xpowers_AXP202_chg_curr_t
// possible values (mA):
// 0/100/125/150/175/200/300/400/500/600/700/800/900/1000
#define PMU_CHG_CUTOFF XPOWERS_AXP202_CHG_VOL_4V2 // battery charge cutoff
// See: xpowers_AXP202_chg_vol_t
// possible values (V):
// 4V1/4V1/4V2/4V35/4V4

// GPS settings
#define HAS_GPS 1 // use on board GPS
#define GPS_SERIAL 9600, SERIAL_8N1, GPIO_NUM_34, GPIO_NUM_12 // UBlox NEO 6M
#define GPS_INT GPIO_NUM_37 // 30ns accurary timepulse generated by NEO 6M Pin #3

// enable only if device has these sensors, otherwise comment these lines
// BME680 sensor on I2C bus
//#define HAS_BME 1 // Enable BME sensors in general
//#define HAS_BME680 SDA, SCL
//#define BME680_ADDR BME68X_I2C_ADDR_LOW // !! connect SDIO of BME680 to GND !!

//#define DISABLE_BROWNOUT 1 // comment out if you want to keep brownout feature

#endif

/*

// <Unknown board> has on board power management by AXP202 PMU chip:


DC2         0.7-2.275V /1.6A  
DC3         0.7-3.5V /1.2A    
LDO1(VRTC)  3.3V /30mA        
LDO2        1.8V-3.3V /200mA  
LDO3        0.7-3.5V /200mA   
LDO4        1.8V-3.3V /200mA  
LDO5/IO0    1.8-3.3V /50mA    

// ??? -> GPS Backup
// ??? -> LORA
// ??? -> GPS

// Wiring for I2C OLED display:
//
// Signal     Header   OLED
// 3V3         7       VCC
// GND         8       GND
// IO22(SCL)   9       SCL
// IO21(SDA)   10      SDA
//

*/
