// clang-format off
// upload_speed 921600
// board ttgo-t-beam

#ifndef _TTGOBEAM_1_2_H
#define _TTGOBEAM_1_2_H

#include <stdint.h>

/* 
Hardware related definitions for TTGO T-Beam board
for T-Beam version T22_V12
pinouts taken from https://github.com/Xinyuan-LilyGO/LilyGo-LoRa-Series/tree/master/schematic

AXP2101 datasheet: https://github.com/eggfly/AXP2101/blob/main/AXP2101_Datasheet_V1.4.pdf

/// Button functions: ///
Power, short press -> set device on / while device is on: goto sleep
Power, long press   -> set device off
User, short press   -> flip display page 
User, long press    -> send a button message
Reset -> reset device
*/

#define HAS_DISPLAY 1
#define MY_DISPLAY_SDA SDA
#define MY_DISPLAY_SCL SCL
#define MY_DISPLAY_RST NOT_A_PIN
//#define MY_DISPLAY_FLIP  1 // use if display is rotated

#define HAS_LORA 1       // comment out if device shall not send data via LoRa
#define CFG_sx1276_radio 1 // HPD13A LoRa SoC
#define HAS_BUTTON GPIO_NUM_38 // middle on board button
#define HAS_LED GPIO_NUM_4 // not present on all T-Beam 1.0 boards
#define LED_ACTIVE_LOW 1

// power management settings
#define HAS_PMU 1 // has AXP2101 chip
#define XPOWERS_CHIP_AXP2101 1
#define PMU_INT GPIO_NUM_35 // battery interrupt
#define PMU_CHG_CURRENT XPOWERS_AXP2101_CHG_CUR_1000MA // battery charge current
// See: xpowers_axp2101_chg_curr_t
// possible values (mA):
// 0/100/125/150/175/200/300/400/500/600/700/800/900/1000
#define PMU_CHG_CUTOFF XPOWERS_AXP2101_CHG_VOL_4V2 // battery charge cutoff
// See: xpowers_axp2101_chg_vol_t
// possible values (V):
// 4V1/4V1/4V2/4V35/4V4

// GPS settings
#define HAS_GPS 1 // use on board GPS
#define GPS_SERIAL 9600, SERIAL_8N1, GPIO_NUM_34, GPIO_NUM_12 // UBlox NEO 6M
#define GPS_INT GPIO_NUM_37 // 30ns accurary timepulse generated by NEO 6M Pin #3

// enable only if device has these sensors, otherwise comment these lines
// BME680 sensor on I2C bus
//#define HAS_BME 1 // Enable BME sensors in general
//#define HAS_BME680 SDA, SCL
//#define BME680_ADDR BME68X_I2C_ADDR_LOW // !! connect SDIO of BME680 to GND !!

//#define DISABLE_BROWNOUT 1 // comment out if you want to keep brownout feature

#endif

/*

// T-Beam V12 has on board power management by AXP2101 PMU chip:

DC1        1.5-3.4V /2A                      -> ESP32 (keep this on!)
DC2        0.5-1.2V,1.22-1.54V /2A
DC3        0.5-1.2V,1.22-1.54V,1.6-3.4V /2A  -> OLED
DC4        0.5-1.2V,1.22-1.84V /1.5A
DC5        1.2V,1.4-3.7V /1A
LDO1(VRTC) 1.8V /30mA                        -> PSRAM

ALDO1      0.5-3.5V /300mA
ALDO2      0.5-3.5V /300mA                   -> LORA
ALDO3      0.5-3.5V /300mA                   -> GPS
ALDO4      0.5-3.5V /300mA
BLDO1      0.5-3.5V /300mA
BLDO2      0.5-3.5V /300mA
DLDO1      0.5-3.3V/300mA (LDO Mode) (Dependent on DC1)
DC1SW      0.5-3.3V/300mA (SW  Mode) (Dependent on DC1)
DLDO2      0.5-1.4V/300mA (LDO Mode) (Dependent on DC4)
DC4SW      0.5-1.4V/300mA (SW  Mode) (Dependent on DC4)
CPUSLDO    0.5-1.4V /30mA            (Dependent on DC4)

N.B.
There are 2 different versions of the AXP2101:
- LDO mode:    DLDO1 / DLDO2
- Switch mode: DC1SW / DC4SW

Note:
    Whether DLDO1/DLDO2/RTCLDO2/GPIO1 can be used depends on the chip.
    It is not available by default.
    RTCLDO1 has a default voltage, which is generally 1.8V by default.
    The voltage value cannot be changed or turned off through the register.

// LDO1 30mA -> GPS Backup
// ALDO2 300mA -> LORA
// ALDO3 300mA -> GPS

// Wiring for I2C OLED display:
//
// Signal     Header   OLED
// 3V3         7       VCC
// GND         8       GND
// IO22(SCL)   9       SCL
// IO21(SDA)   10      SDA
//

*/
