{
 "title": "ESP32-Paxcounter",
 "description": "ESP32-Paxcounter dashboard",
 "tags": [
  "LoRaWAN",
  "InfluxDB"
 ],
 "time": { "from": "2021-07-22T12:00:00.000Z", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Sélectionner la ruche",
    "query": "SHOW TAG VALUES WITH KEY = \"device\""
   }
  ]
 },
 "panels": [
  {
   "title": "Raw values",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Données brutes",
     "type": "table",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 2 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "*" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Location",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Géolocalisation",
     "type": "pr0ps-trackmap-panel",
     "gridPos": { "h": 17, "w": 10, "x": 0, "y": 2 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "query": "SELECT median(\"latitude\"), median(\"longitude\") FROM \"measurements\" WHERE (\"device\" = 'pax_counter') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "latitude" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "longitude" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Longitude",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 10, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "longitude" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Latitude",
     "type": "graph",
     "gridPos": { "h": 8, "w": 6, "x": 16, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "1m" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "latitude" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Altitude",
     "type": "graph",
     "gridPos": { "h": 9, "w": 4, "x": 10, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "altitude" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Satellites",
     "type": "graph",
     "gridPos": { "h": 9, "w": 4, "x": 14, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "sats" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Erreur HDOP",
     "type": "graph",
     "gridPos": { "h": 9, "w": 4, "x": 18, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "hdop" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "BME sensor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "celsius" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "temperature" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Humidité",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 3 },
     "yaxes": [
      { "format": "humidity" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "humidity" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Pressure",
     "type": "graph",
     "gridPos": { "h": 10, "w": 5, "x": 12, "y": 3 },
     "yaxes": [
      { "format": "pressurehpa" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "pressure" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "air",
     "type": "graph",
     "gridPos": { "h": 10, "w": 5, "x": 17, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "air" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "PAX",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Conter Pax, Ble, Wifi",
     "type": "graph",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Bluetooth connection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "ble" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      },
      {
       "alias": "WiFi connection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "wifi" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      },
      {
       "alias": "Passenger (PAX) connection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "pax" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    },
    {
     "title": "Conter Ens, Pax",
     "type": "graph",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Passenger (PAX) connection",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "pax" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "ens" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Batterie",
     "type": "graph",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "mvolt" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "voltage" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=~", "value": "/^$device$/" }
       ]
      },
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "measurements",
       "select": [
        [
         { "params": [ "longitude" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "device", "operator": "=", "value": "pax_counter" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Gateway",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "RSSI Gateway",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "dB" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gateway",
       "select": [
        [
         { "params": [ "rssi" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "SNR Gateway",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 6 },
     "yaxes": [
      { "format": "dB" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gateway",
       "select": [
        [
         { "params": [ "snr" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Bandwith Gateway",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gateway",
       "select": [
        [
         { "params": [ "bandwidth" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Spreading factor Gateway",
     "type": "graph",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 6 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "device" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "gateway",
       "select": [
        [
         { "params": [ "spreading_factor" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "raw values gateway",
     "type": "table",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 16 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "gateway",
       "select": [
        [
         { "params": [ "*" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}